version: '3'
services:
  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'dental_db'
      MYSQL_USER: 'dental'
      MYSQL_PASSWORD: 'dental_password'
      MYSQL_ROOT_PASSWORD: 'dental_root_password'

  redis:
    image: "redis:alpine"

  frontend:
    build:
      context: ./
      dockerfile: docker/frontend/frontend.Dockerfile
    volumes:
      - ./static/admin:/usr/share/nginx/html/admin
      - ./static/rest_framework:/usr/share/nginx/html/rest_framework
      - ./static/django_extension:/usr/share/nginx/html/django_extension
      - ./static/django_toolbar:/usr/share/nginx/html/django_toolbar
      - ./media:/usr/share/nginx/html/media    
      - ./vue:/usr/share/nginx/html
    restart: "always"
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: docker/backend/backend.Dockerfile
    command: ["./docker/entry.sh"]
    restart: "always"
    ports:
      - "3000:3000"
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
    environment:
      SECRET_KEY: 'tg7703_ddewirye6t0d^mam7-=42&!k&wv5dhi$$(35kouzi3ks'
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: db
      DATABASE_NAME: dental_db
      DATABASE_USER: dental
      DATABASE_PASSWORD: dental_root_password
      DATABASE_PORT: 3306
  celery:
    build: 
      context: ./
      dockerfile: docker/app.Dockerfile
    command: celery -A dental worker -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis
  celery-beat:
    build: 
      context: ./
      dockerfile: docker/app.Dockerfile
    command: celery -A dental beat -l info
    volumes:
      - .:/code
    depends_on:
      - db
      - redis

