version: '3'
services:
  db:
    image: mariadb:latest
    ports:
      - "3068:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'd_db'
      MYSQL_USER: 'dhub'
      MYSQL_PASSWORD: 'd_password'
      MYSQL_ROOT_PASSWORD: 'dental_root_password'

  # redis:
  #   image: "redis:alpine"

  frontend:
    build:
      context: ./
      dockerfile: docker/frontend/frontend.Dockerfile
    volumes:
      - ./static/static:/usr/share/nginx/html/static
      - ./media:/usr/share/nginx/html/media
      - ./vue:/usr/share/nginx/html
    restart: "always"
    ports:
      - "6064:6064"
    depends_on:
      - backend
  backend:
    build:
      context: ./
      dockerfile: docker/backend/backend.Dockerfile
    command: ["./docker/entry.sh"]
    restart: "always"
    ports:
      - "6065:6065"
    volumes:
      - .:/code
    depends_on:
      - db
      # - redis
    environment:
      SECRET_KEY: 'tg7703_ddewirye6t0d^mam7-=42&!k&wv5dhi$$(35kouzi3ks'
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: db
      DATABASE_NAME: d_db
      DATABASE_USER: dhub
      DATABASE_PASSWORD: d_root_password
      DATABASE_PORT: 3306
  # celery:
  #   build:
  #     context: ./
  #     dockerfile: docker/app.Dockerfile
  #   command: celery -A dental worker -l info
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  #     - redis
  # celery-beat:
  #   build:
  #     context: ./
  #     dockerfile: docker/app.Dockerfile
  #   command: celery -A dental beat -l info
  #   volumes:
  #     - .:/code
  #   depends_on:
  #     - db
  #     - redis
